### ISSUE TITLE
Support specific virtualenv folder

### ISSUE THREAD

**Issue by dzen** [pghilardi/atom-python-virtualenv#12]
For some reason, my virtualenv are created by virtualenvwrapper in a distinct folder, not in $HOME/.virtualenvs.

Is there a way to provide a configurable virtualenv location ?

Thank you.

**Comment by pghilardi** [comment]
@dzen ,

I am working to support this as soon as possible. I will expose the $HOME variable of your virtualenv. I will return to you when I have finished. I am working on branch [auto-discovery](https://github.com/pghilardi/atom-python-virtualenv/tree/auto_discovery).

**Comment by pghilardi** [comment]
Hey @dzen ,

Update to the last version 0.9.0 and probably the plug-in will work for you and get the right envs from the virtualenvwrapper. In this version I am getting the envs from the WORKON_HOME environment variable, so this probably will work. Let me know!

Thanks
