### ISSUE TITLE
Virtual env created after closing the dialog box

### ISSUE THREAD

**Issue by scryver** [pghilardi/atom-python-virtualenv#23]
When I use 'ctrl-cmd-alt-v' type in some text and press escape, the dialog window disappears, so far so good.
After that I go to any text box, type something and press enter, and voila a new virtualenv is created and switched to, using the text I typed in the dialog window. I guess the focus isn't lost or something and the 'core:confirm' bubbles through to the MakeDialog class. Too little experience in Atom/Coffee to know exactly what's going on but that is where my debugging led me.

**Comment by pghilardi** [comment]
@scryver ,

Fixed on version 0.15.0. Thanks for the report!
