### ISSUE TITLE
custom WORKON_HOME doesn't take effect

### ISSUE THREAD

**Issue by fzhcary** [pghilardi/atom-python-virtualenv#25]
In atom, settings_view, manage atom-python-virtualenv UI, after user put a new WORKON_HOME such as $HOME/Envs, it doesn't take effect. I mean
- mkvirtualenv still create vituralenv in $HOME folder instead of the custom WORKON_HOME.

When I look at the code, 
`          if customWorkOnHome?
            customWorkOnHome = customWorkOnHome.replace('$HOME', process.env.HOME)
            if fs.existsSync customWorkOnHome
              @getVirtualEnvs([customWorkOnHome], true)`

it didn't update the wrapper, customWorkOnHome is parsed, but not used anywhere.
maybe you need `wrapper = customWorkOnHome` at the end

**Comment by pghilardi** [comment]
@fzhcary ,

You are right. I will fix this soon and I will let you know when a new version is released with this bug fix.

**Comment by pghilardi** [comment]
@fzhcary ,

Fixed on version 0.15.0. Thanks for the report!
