### ISSUE TITLE
Environment values in activate not being picked up

### ISSUE THREAD

**Issue by pasherman** [pghilardi/atom-python-virtualenv#38]
I have environment value in the virtual environment activate file and they are not being picked up when trying to run from within atom. Any ideas?

**Comment by isam-os** [comment]
this pack not work for me too .. why ? .. think author is lost )) 

### windows and python3 not work

TRY CHANGE packages\atom-python-virtualenv\lib\virtualenv-manager.coffee IN ATOM


          if process.platform == 'win32'
            cmd = ' dir /s /b activate'
          else
            cmd = 'find "$(pwd - P)" -follow -maxdepth 4 -name "activate"'

TO 


```
          if process.platform == 'win32'
=====>>>>> cmd = ' dir /s /b activate.bat'
          else
            cmd = 'find "$(pwd - P)" -follow -maxdepth 4 -name "activate"
```

**Comment by pghilardi** [comment]
Hello guys! 

I do not have much time to support this package, but I will try to check the last issues to have a minimum working plug-in. Testing in windows and linux.

Thanks for the report!

**Comment by pghilardi** [comment]
Changed to activate.bat. Try version 1.0.3.
