### ISSUE TITLE
Activating virtual environment manually

### ISSUE THREAD

**Issue by davidlever** [pghilardi/atom-python-virtualenv#42]
Hi,

I am trying to select a virtual environment in Atom using your plugin (version 1.0.4). The target virtualenv is in the root folder of my project (i.e. project/venv), but when I input the path to the venv manually (C:/Users/myname/Documents/project) under 'Additional virtualenvs', it does not show up when I try select it (it says 'No matches found'). How is this possible?

Do I have to use a $HOME variable in the path? If so, I am unable to find out how to set this variable on Windows 10, even after searching the web for a couple of hours (e.g. the instructions at https://danlimerick.wordpress.com/2011/07/11/git-for-windows-tip-setting-home-and-the-startup-directory/ does not work). 

Lastly, if I deselect 'Get virtualenvs from the home folder' and 'Get virtualenvs from the virtualenvwrapper folder', I should be able to specify the path without $HOME right?

Thank you!

Best,

David

**Comment by StefanBrand** [comment]
#30 has a solution for me:

In the `WORKON_HOME` preference, I have entered `C:\Users\Stefan\Envs` and Atom finds my virtual environments.

**Comment by pghilardi** [comment]
As stated by @StefanBrand, you can change the WORKON_HOME on settings or you can add virtualenv paths manually in the addiional paths.
