### ISSUE TITLE
Use with pipenv?

### ISSUE THREAD

**Issue by harmtemolder** [pghilardi/atom-python-virtualenv#51]
I see a to-do in your README to add support for [pipenv](https://pipenv.pypa.io/en/latest/index.html). I'd like to +1 that.

I'm also willing to help you develop and test that.

**Comment by harmtemolder** [comment]
Note that pipenv honors `WORKON_HOME` ([source](https://pipenv.pypa.io/en/latest/advanced/#custom-virtual-environment-location)), but I actually use `PIPENV_VENV_IN_PROJECT` instead

**Comment by pghilardi** [comment]
Hi @harmtemolder,

Thank you for wanting to help this project. 

Unfortunately I am not updating this project anymore, as Atom will die this month: https://github.blog/2022-06-08-sunsetting-atom/

My suggestion would be to use Visual Studio Code as a replacement.
