### ISSUE TITLE
Add support to Windows platform

### ISSUE THREAD

**Issue by pghilardi** [pghilardi/atom-python-virtualenv#6]
Ideas:

* Use the https://pypi.python.org/pypi/virtualenvwrapper-win package

Problems:

I tried to change the PATH dynamically but it isn't working in Windows:
https://discuss.atom.io/t/change-process-path-dynamically-inside-a-package/

**Comment by Heuertje** [comment]
Hi @pghilardi did you end up solving this issue?

**Comment by pghilardi** [comment]
@Heuertje ,

Not solved yet. I didn`t invest more time on this.

**Comment by pghilardi** [comment]
@Heuertje 

I am working on this right now. I have an idea how to solve the problem. Probably I will have good news about this.

**Comment by pghilardi** [comment]
@Heuertje,

Try the new version 1.0.0 with added support to Windows. Let me know!

**Comment by Heuertje** [comment]
Awesome! At first sight it seems to work like a charm! Thank you very much for the quick fix :DD

**Comment by pghilardi** [comment]
Thanks!

Keep testing and let me know about bugs :)
