### ISSUE TITLE
Modify readme for easier understanding

### ISSUE THREAD

**Issue by AndreasGerken** [pghilardi/atom-python-virtualenv#9]
Hi,
i'm quite new to virtualenv but i know how to use it without your plugin. I was quite happy that there is a plugin for atom, and i made a new virtualenv with it and activated it.
Now i have no idea where it was installed, there is nothing new in my project folder.
Also i would not know how to install new packages to it.
Thank you for maintaining the project!

Andi

**Comment by pghilardi** [comment]
@AndreasGerken ,

I will add some enhancements to this plug-in, like showing the current virtualenv and the current path for the current virtualenv. This will help new users. I also have the idea to support pip with virtualenv, and allows the install of new packages.

**Comment by pghilardi** [comment]
@AndreasGerken ,

I have updated the README explainning how to use virtualenvs inside the home folder. Could you install the latest plug-in version and try to configure again? Let me know here if you still have problems.
